In [2]:
import pandas as pd 
import numpy as np

In [40]:
df1 = pd.read_csv('../data/retail_10k.csv')
df2 = pd.read_csv('../data/transactions_v1.csv')
df3 = pd.read_csv('../data/spending_patterns_detailed.csv')
df4 = pd.read_csv('../data/transactions_v2.csv')

In [36]:
df1.head()

        Category              Item  Total Spent Transaction Date
0        Housing              Rent       985.04       2023-08-17
1      Utilities  Electricity Bill       226.28       2023-03-31
2  Subscriptions           Spotify         8.28       2023-08-27
3  Subscriptions    Gym Membership        11.96       2024-10-27
4        Housing          Mortgage      1424.97       2023-01-07

In [37]:
df2.head()

,date,description,amount,label,source
0,2023-08-17,pos purchase rent,985.04,other,retail_simulated_bank
1,2023-03-31,Online*Purchase*Electricity*Bill,226.28,other,retail_simulated_bank
2,2023-08-27,Pos Purchase Spotify 166573,8.28,other,retail_simulated_bank
3,2024-10-27,online*purchase*gym*membership,11.96,other,retail_simulated_bank
4,2023-01-07,CARD/PMT/MORTGAGE 226177,1424.97,other,retail_simulated_bank

In [38]:
df3.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28

In [7]:
print("Total Length of each dataset","\n")
print(" Retail 10K : ", len(df1), "\n",
      "transaction_v1 : ",len(df2),"\n",
      "spending pattern data :" ,len(df3)
      )

Total Length of each dataset

 Retail 10K :  10000
 transaction_v1 :  10000
 spending pattern data : 10000

### The EDA OF ALL DATA TYPES

In [8]:
df3.tail()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04

In [9]:
df3.dtypes

Customer ID          object
Category             object
Item                 object
Quantity              int64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

In [10]:
df3.columns

Index(['Customer ID', 'Category', 'Item', 'Quantity', 'Price Per Unit',
       'Total Spent', 'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [13]:
print(df1["Category"].unique())

['Housing' 'Utilities' 'Subscriptions' 'Other' 'Transportation'
 'Groceries' 'Dining']

In [12]:
df3['Category'].unique()

array(['Groceries', 'Friend Activities', 'Housing and Utilities',
       'Fitness', 'Gifts', 'Transportation', 'Travel', 'Personal Hygiene',
       'Hobbies', 'Shopping', 'Medical/Dental', 'Food', 'Subscriptions'],
      dtype=object)

In [14]:
df3.tail()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04

In [16]:
df2.head()

,date,description,amount,label,source
0,2023-08-17,pos purchase rent,985.04,other,retail_simulated_bank
1,2023-03-31,Online*Purchase*Electricity*Bill,226.28,other,retail_simulated_bank
2,2023-08-27,Pos Purchase Spotify 166573,8.28,other,retail_simulated_bank
3,2024-10-27,online*purchase*gym*membership,11.96,other,retail_simulated_bank
4,2023-01-07,CARD/PMT/MORTGAGE 226177,1424.97,other,retail_simulated_bank

In [17]:
df1.head()

        Category              Item  Total Spent Transaction Date
0        Housing              Rent       985.04       2023-08-17
1      Utilities  Electricity Bill       226.28       2023-03-31
2  Subscriptions           Spotify         8.28       2023-08-27
3  Subscriptions    Gym Membership        11.96       2024-10-27
4        Housing          Mortgage      1424.97       2023-01-07

In [18]:
df1['Item'].unique()

array(['Rent', 'Electricity Bill', 'Spotify', 'Gym Membership',
       'Mortgage', 'Online Purchase', 'Train Ticket', 'Milk',
       'Misc Expense', 'Chicken', 'Uber Ride', 'Gas Bill', 'Restaurant',
       'Fast Food', 'Water Bill', 'Internet Bill', 'Netflix',
       'Vegetables', 'Food Delivery', 'Bread', 'Fuel', 'Rice', 'Bus Pass',
       'Eggs'], dtype=object)

In [19]:
df2['description'].unique()

array(['pos purchase rent', 'Online*Purchase*Electricity*Bill',
       'Pos Purchase Spotify 166573', ..., 'CARD PAYMENT MORTGAGE 780898',
       'card-pmt-electricity-bill 405393', 'Card Pmt Fast Food 319821'],
      dtype=object)

In [20]:
df2['description'].value_counts()

description
Online Purchase Online Purchase           34
Pos Purchase Online Purchase              33
pos purchase rent                         30
Pos Purchase Misc Expense                 28
Pos Purchase Rent                         28
                                          ..
ONLINE PURCHASE ONLINE PURCHASE 873308     1
Online Purchase Gas Bill 650319            1
CARD PAYMENT WATER BILL 289260             1
pos/purchase/fast/food 592785              1
Card Pmt Fast Food 319821                  1
Name: count, Length: 6943, dtype: int64

In [23]:
df2.isna().mean()

date           0.0
description    0.0
amount         0.0
label          0.0
source         0.0
dtype: float64

In [22]:
print(df2["label"].value_counts(normalize=True))

label
other             0.7142
groceries         0.1436
transportation    0.1422
Name: proportion, dtype: float64

In [24]:
df2["desc_len"] = df2["description"].str.len()
print(df2.groupby("label")["desc_len"].mean().sort_values())

label
groceries         21.408078
transportation    22.573840
other             27.197144
Name: desc_len, dtype: float64

In [28]:
print(df2.groupby("label")["amount"].describe()[["mean","50%","min","max"]])

                      mean    50%   min      max
label
groceries        75.903733  77.06  3.01   149.91
other           327.038353  92.82  3.08  1999.05
transportation   78.623572  79.16  3.08   149.84

In [29]:
df2.describe()

            amount      desc_len
count  10000.00000  10000.000000
mean     255.65084     25.708400
std      460.17212      6.045364
min        3.01000      9.000000
25%       34.76500     21.000000
50%       86.71500     26.000000
75%      139.94500     30.000000
max     1999.05000     39.000000

In [32]:
df1.head()

        Category              Item  Total Spent Transaction Date
0        Housing              Rent       985.04       2023-08-17
1      Utilities  Electricity Bill       226.28       2023-03-31
2  Subscriptions           Spotify         8.28       2023-08-27
3  Subscriptions    Gym Membership        11.96       2024-10-27
4        Housing          Mortgage      1424.97       2023-01-07

## Generating Bank Transaction Similar Labels

In [34]:
['Rent', 'Electricity Bill', 'Spotify', 'Gym Membership',
 'Mortgage', 'Online Purchase', 'Train Ticket', 'Milk',
 'Uber Ride', 'Gas Bill', 'Restaurant', 'Fast Food',
 'Water Bill', 'Internet Bill', 'Netflix', 'Vegetables',
 'Food Delivery', 'Bread', 'Fuel', 'Rice', 'Bus Pass', 'Eggs']

['Rent',
 'Electricity Bill',
 'Spotify',
 'Gym Membership',
 'Mortgage',
 'Online Purchase',
 'Train Ticket',
 'Milk',
 'Uber Ride',
 'Gas Bill',
 'Restaurant',
 'Fast Food',
 'Water Bill',
 'Internet Bill',
 'Netflix',
 'Vegetables',
 'Food Delivery',
 'Bread',
 'Fuel',
 'Rice',
 'Bus Pass',
 'Eggs']